"""add enums

Revision ID: 65697479b564
Revises: d4b9c8df77d2
Create Date: 2026-07-16 18:51:20.259108

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "65697479b564"
down_revision: str | Sequence[str] | None = "d4b9c8df77d2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
